### ISSUE TITLE
Not compatible with iOS 13

### ISSUE THREAD

**Issue by RaresAil** [BrianCorbin/SwiftRangeSlider#33]
![](https://i.imgur.com/kR36mI7.png)

**Comment by beyerss** [comment]
This hasn't been updated in a very long time. If you'd like to use it, I have a fork of this located here: https://github.com/beyerss/SwiftRangeSlider

You can install it wit:
`pod 'SwiftRangeSlider', :git=> 'git@github.com:beyerss/SwiftRangeSlider.git'`

This does work with the latest version of Xcode. And if you have any changes you would like to make I can publish this officially through cocoa pods so that the community has a maintainable version again.

**Comment by prateekpulp** [comment]
Analyzing dependencies
Pre-downloading: `SwiftRangeSlider` from `git@github.com:beyerss/SwiftRangeSlider.git`

[!] Error installing SwiftRangeSlider
[!] Failed to download 'SwiftRangeSlider': [!] /usr/bin/git clone git@github.com:beyerss/SwiftRangeSlider.git /var/folders/gs/2527xmz91810cwkvf1f2_f6r0000gp/T/d20200320-11680-69xree --template= --single-branch --depth 1

Cloning into '/var/folders/gs/2527xmz91810cwkvf1f2_f6r0000gp/T/d20200320-11680-69xree'...
Warning: Permanently added the RSA host key for IP address '13.234.176.102' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by beyerss** [comment]
@prateekpulp can you clone that repository directly? It is set to be public so i'm not sure why you wouldn't have the correct access rights
