### ISSUE TITLE
Slider view does not respond when in TableViewCell

### ISSUE THREAD

**Issue by irfanG** [BrianCorbin/SwiftRangeSlider#9]
I am trying to use the slider in TVC but the slider does not respond.

Could you help me understand what needs to be done? 

Thanks

**Comment by BrianCorbin** [comment]
Hmm, could you gimme an example of the issue, maybe a project with the issue so I can debug it? Thanks!

**Comment by vualeks** [comment]
Hey,

I've also tried and have the same issue. It could be that gestures don't get to the slider. I've put it in view controller that is inside pageview controller and it doesn't get the gestures. When it is outside of the container, on main view, it works ok.

**Comment by BrianCorbin** [comment]
Hmm.. I've just pushed an update that I'm hoping should fix it (by the way, lots of new features and fixes!). Let me know if you're still having issues (as I didn't explicitly look into this bug), let me know and I'll make it top priority.

**Comment by vualeks** [comment]
Nope, still the same.

Also, fix the quotes in Readme file, from pod ‘SwiftRangeSlider’ to pod 'SwiftRangeSlider'
Pod complain about that :)

**Comment by vualeks** [comment]
Oh, man, I'm sorry, it actually works. I'm pretty new to IOS so this might be expected behaviour, but looks really strange to an android user :)
When your slider is in main view and there is no other possible gesture over it, if works like I would expect it to work, just tap and move the slider and that's it, it works. When the slider is inside page view controller (which catches left/right swipes to turn pages) you first need to hold the slider (long tap on thumb) and it will move. If you just tap on it and immediately start sliding, page view controller gets the gesture and slides the page which then looks like the slider is not catching the gesture.

The question now is: can this somehow be overturned in favour of the slider, that it works just on tap and slide, and not page swiping?

Sorry again if I wasted your time trying to figure this out.
